### ISSUE TITLE
Strange thing I'm not sure if it's clientside or not.

### ISSUE THREAD

**Issue by grinching-it** [colaclanth/sstv#7]
It was working perfectly fine a couple days ago, and now when I do something exactly the same, it returns this on my terminal:

```
Traceback (most recent call last):
  File "/usr/bin/sstv", line 33, in <module>
    sys.exit(load_entry_point('sstv==0.1', 'console_scripts', 'sstv')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/sstv-0.1-py3.11.egg/sstv/__main__.py", line 18, in main
  File "/usr/lib/python3.11/site-packages/sstv-0.1-py3.11.egg/sstv/command.py", line 108, in start
  File "/usr/lib/python3.11/site-packages/sstv-0.1-py3.11.egg/sstv/decode.py", line 45, in __init__
  File "/usr/lib/python3.11/site-packages/PySoundFile-0.9.0.post1-py3.11.egg/soundfile.py", line 372, in read
    with SoundFile(file, 'r', samplerate, channels,
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/PySoundFile-0.9.0.post1-py3.11.egg/soundfile.py", line 740, in __init__
    self._file = self._open(file, mode_int, closefd)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/PySoundFile-0.9.0.post1-py3.11.egg/soundfile.py", line 1264, in _open
    _error_check(_snd.sf_error(file_ptr),
  File "/usr/lib/python3.11/site-packages/PySoundFile-0.9.0.post1-py3.11.egg/soundfile.py", line 1455, in _error_check
    raise RuntimeError(prefix + _ffi.string(err_str).decode('utf-8', 'replace'))
RuntimeError: Error opening <_io.BufferedReader name='/home/killer/Downloads/Winter_trail.mp4'>: Format not recognised.
```

Is it my problem or the program's? How could I fix?

**Comment by grinching-it** [comment]
I'm not very advanced user, just a heads up..

**Comment by bmyoungquist** [comment]
`RuntimeError: Error opening <_io.BufferedReader name='/home/killer/Downloads/Winter_trail.mp4'>: Format not recognised.`

It looks like you are trying to decode a video file instead of an audio file which is unsupported
